#!/bin/bash

# Somerled Pages - A program for creating family encyclopedias
# Copyright (C) 2023 Jack J. Miller
# Licensed under version 3 of the GNU General Public License

PROGRAM_PATH=/home/jack/Development/Somerled-Pages

let "EXITCODE = 0"

if [ "$1" == "init" ]; then

    mkdir $1

elif [ "$1" == "build" ]; then

    [ ! -d build/ ] && mkdir build/
    [ ! -d build/wiki ] && mkdir build/wiki
    [ ! -d build/sheet ] && mkdir build/sheet

    node $PROGRAM_PATH/main.js $( pwd ) $@ || let "EXITCODE = 1"

    if [ "$EXITCODE" == "0" ]; then
        [ -d wiki/ ] && rm -r wiki/
        [ -d sheet/ ] && rm -r sheet/
        mv build/wiki/ wiki/
        mv build/sheet/ sheet/
    fi

elif [[ $# -eq 2 && "$1" == "new-article" ]]; then

    PAGE_NAME=$2

    if [ -f data/wiki_source/$PAGE_NAME ]; then
        echo Error: page $PAGE_NAME already exists
        exit 1
    fi

    cp res/wiki_boilerplate data/wiki_source/$PAGE_NAME

    echo Page created: $PAGE_NAME

elif [[ $# -eq 2 && "$1" == "new-sheet" ]]; then

    PAGE_NAME=$2

    if [ -f data/sheet_source/$PAGE_NAME ]; then
        echo Error: page $PAGE_NAME already exists
        exit 1
    fi

    cp res/sheet_boilerplate data/sheet_source/$PAGE_NAME

    echo Page created: $PAGE_NAME

elif [[ $# -ge 2 && "$1" == "add-media" ]]; then

    for (( i=2; i<=$#; i+=1 ))
    do
        MEDIA_NAME=${!i}

        if [ -f media/$MEDIA_NAME ]; then
            echo Error: media $MEDIA_NAME already exists
            exit 1
        else
            echo $MEDIA_NAME
            cp $MEDIA_NAME media/$MEDIA_NAME
            mat2 --inplace media/$MEDIA_NAME
            cp res/metadata_boilerplate.json media/$MEDIA_NAME.json
        fi

    done

else

    if [ "$1" != "--help" ]; then
        echo "Invalid parameters"
        echo
    fi

    echo "usage:"
    echo "  somerled-pages build [<build-name>]  build the encyclopedia"
    echo "  somerled-pages new-article <name>    create a new article"
    echo "  somerled-pages new-sheet <name>      create a new sheet"
    echo "  somerled-pages add-media <files>     add a file to the media repository"
    echo "  somerled-pages --help                display this help page"

fi

exit $EXITCODE
