#!/bin/bash

# Somerled Pages - A program for creating family encyclopedias
# Copyright (C) 2023-2024 Jack J. Miller
# Licensed under version 3 of the GNU General Public License

PROGRAM_PATH=/home/jack/Development/Somerled-Pages

ListBuilds() {
    echo "Available Builds:"
    ls data/builds | sed 's/\.json$//g'
}

let "EXITCODE = 0"

if [[ $# -eq 2 && "$1" == "init" ]]; then

    if [ ! -z $2 ]; then
        mkdir $2
        cp -r $PROGRAM_PATH/res/initial-project/* $2
    else
        echo A project titled $2 already exists
    fi

elif [ "$1" == "build" ]; then

    rm build/media/* build/sources/* build/sheet/* build/wiki/* build/res/*.css
    rm -r wiki/*
    cp $PROGRAM_PATH/res/*.css build/res/
    node $PROGRAM_PATH/main.js $( pwd ) $@ || let "EXITCODE = 1"

    if [ "$EXITCODE" == "0" ]; then
        [ -d wiki/ ] && rm -r wiki/
        [ -d sheet/ ] && rm -r sheet/
        cp -r build/wiki/ wiki/
        cp -r build/sheet/ sheet/
    fi

elif [[ $# -eq 2 && "$1" == "new-article" ]]; then

    PAGE_NAME=$2

    if [ -f data/wiki_source/$PAGE_NAME ]; then
        echo Error: page $PAGE_NAME already exists
        exit 1
    fi

    cp res/wiki_boilerplate data/wiki_source/$PAGE_NAME

    echo Page created: $PAGE_NAME

elif [[ $# -eq 2 && "$1" == "new-sheet" ]]; then

    PAGE_NAME=$2

    if [ -f data/sheet_source/$PAGE_NAME ]; then
        echo Error: page $PAGE_NAME already exists
        exit 1
    fi

    cp res/sheet_boilerplate data/sheet_source/$PAGE_NAME

    echo Page created: $PAGE_NAME

elif [[ $# -ge 2 && "$1" == "add-media" ]]; then

    for (( i=2; i<=$#; i+=1 ))
    do
        MEDIA_NAME=${!i}

        if [ -f media/$MEDIA_NAME ]; then
            echo Error: media $MEDIA_NAME already exists
            exit 1
        else
            echo $MEDIA_NAME
            cp $MEDIA_NAME media/$MEDIA_NAME
            mat2 --inplace media/$MEDIA_NAME
            cp res/metadata_boilerplate.json media/$MEDIA_NAME.json
        fi

    done

elif [[ $# -eq 1 && "$1" == "list-builds" ]]; then

    ListBuilds

else

    if [ "$1" != "--help" ]; then
        echo "Invalid parameters"
        echo
    fi

    echo "usage:"
    echo "  somerled-pages build [<build-name>]  build the encyclopedia"
    echo "  somerled-pages new-article <name>    create a new article"
    echo "  somerled-pages new-sheet <name>      create a new sheet"
    echo "  somerled-pages add-media <files>     add a file to the media repository"
    echo "  somerled-pages --help                display this help page"

fi

exit $EXITCODE
